# project definitions

topnav_title: Jisc LA Documentation
homepage_title: Jisc LA Documentation
site_title: Jisc LA Documentation
project_folder: 
disqus_shortname: idrbwjekyll
# variables


sidebar_tagline: Recipies
sidebar_version: Revision 1.0
theme_file: theme-blue.css
pdf_file_name: mydoc_designers_pdf.pdf

# the algolia entries here are experimental only.



exclude:
  - _site
  - _drafts
  - configs/



highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

